# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
deluge-auth: localclient:test

- &juicy age1zasvffe7jux3eghf2zqvdg8ha6tagdpqeddpn9e8r7cleemgt33q77cwq8

- &serverdante age1w2rx4rmpeu56f5rwjpk53n5z4xcnqatfq937tcg5fzumdx3q935qh2xcnf

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    age:
      - *juicy
      - *serverdante
