keys:
  - &host_leo age18a63tam58c3079l7dmf7udchwycerytpectqqjg22s0yxt7yvsqs0jnfd6
creation_rules:
  - path_regex: hosts/secrets.yaml
    key_groups:
    - age:
      - *host_leo
  - path_regex: hosts/leo/secrets.yaml
    key_groups:
    - age:
      - *host_leo
  - path_regex: users/secrets.yaml
    key_groups:
    - age:
      - *host_leo
  - path_regex: users/juicy/secrets.yaml
    key_groups:
    - age:
      - *host_leo
